;; for compatibility with older Aquamacs versions
; (defvar aquamacs-140-custom-file-upgraded t)
; (unless (fboundp 'auto-detect-longlines) (defun auto-detect-longlines () t))

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(ac-auto-start 3)
 '(ac-trigger-key "<C-tab>")
 '(adaptive-fill-mode nil)
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 172 t)
 '(bmkp-auto-light-when-jump (quote any-bookmark))
 '(bmkp-bmenu-commands-file "~/.emacs.d/var/bmk-bmenu-commands.el")
 '(bmkp-bmenu-state-file "~/.emacs.d/var/bmk-bmenu-state.el")
 '(bmkp-prompt-for-tags-flag t)
 '(buffer-stack-show-position (quote buffer-stack-show-position-buffers))
 '(column-number-mode t)
 '(confirm-kill-emacs (quote y-or-n-p))
 '(dabbrev-case-fold-search nil)
 '(default-frame-alist (quote ((tool-bar-lines . 0) (menu-bar-lines . 1) (foreground-color . "Black") (background-color . "White") (cursor-type . box) (cursor-color . "Red") (fringe) (left-fringe . 5) (right-fringe . 5))))
 '(enable-recursive-minibuffers nil)
 '(eproject-completing-read-function (quote eproject--ido-completing-read))
 '(espresso-indent-level 4)
 '(flymake-allowed-file-name-masks (quote (("\\.py" flymake-pycheckers-init))))
 '(focus-follows-mouse nil)
 '(global-hl-line-mode t)
 '(ibuffer-display-summary nil)
 '(ibuffer-eliding-string "…")
 '(ido-everywhere t)
 '(ido-max-prospects 8)
 '(ido-mode (quote both) nil (ido))
 '(ido-save-directory-list-file "~/.emacs.d/var/ido.last")
 '(ido-use-url-at-point t)
 '(iedit-occurrence-face (quote match))
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote left))
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-buffer-choice "~/TODO")
 '(markdown-command "~/bin/markdown")
 '(org-src-fontify-natively t)
 '(org-todo-keywords (quote ((sequence "TODO" "DONE" "WAITING" "SOMEDAY"))))
 '(overflow-newline-into-fringe t)
 '(pabbrev-read-only-error nil)
 '(pocoo-always-private t)
 '(py-continuation-offset 2)
 '(py-import-check-point-max 200)
 '(python-continuation-offset 2)
 '(recentf-mode t)
 '(recentf-save-file "~/.emacs.d/var/recent-files")
 '(require-final-newline nil)
 '(scroll-bar-mode nil)
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(simplenote-directory "/Users/jek/.emacs.d/var/simplenote/")
 '(simplenote-email "jek@discorporate.us")
 '(simplenote-notes-mode (quote markdown-mode))
 '(simplenote-password "agbd2LSB.snc")
 '(todoo-file-name "~/TODO")
 '(track-eol t)
 '(truncate-partial-width-windows nil)
 '(uniquify-buffer-name-style (quote reverse) nil (uniquify))
 '(uniquify-separator ":")
 '(visible-mark-faces (quote (visible-mark-face-5 visible-mark-face-4 visible-mark-face-3 visible-mark-face-2 visible-mark-face)))
 '(visible-mark-max 5)
 '(visual-line-fringe-indicators (quote (left-curly-arrow nil)))
 '(vline-face (quote hl-line))
 '(w3m-arrived-file "/Users/jek/.emacs.d/var/w3m/.arrived")
 '(w3m-bookmark-file "/Users/jek/.emacs.d/var/w3m/bookmark.html")
 '(w3m-default-save-directory "~/Downloads")
 '(w3m-form-textarea-directory "/Users/jek/.emacs.d/var/w3m/.textarea")
 '(w3m-init-file "~/.emacs.d/var/w3m-init")
 '(w3m-profile-directory "~/.emacs.d/var/w3m")
 '(w3m-session-file "/Users/jek/.emacs.d/var/w3m/.sessions")
 '(w3m-use-cookies t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(diff-added ((t (:inherit diff-changed :foreground "blue"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "red"))))
 '(dropdown-list-selection-face ((t (:inherit region))))
 '(flyspell-duplicate ((t (:foreground "Gold3" :underline t))))
 '(flyspell-incorrect ((t (:foreground "OrangeRed" :underline t))))
 '(fringe ((((class color) (background light)) (:background "grey97"))))
 '(mode-line ((((class color) (min-colors 88)) (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :height 1.1 :family "optima"))))
 '(py-builtins-face ((t (:foreground "indian red"))) t)
 '(py-exception-name-face ((t (:foreground "firebrick" :weight bold))) t)
 '(py-pseudo-keyword-face ((t (:foreground "dodger blue"))) t)
 '(rst-mode-default ((t (:inherit text-mode-default :slant normal :weight normal :height 120 :family "monaco"))) t)
 '(sml-modeline-end-face ((t nil)))
 '(sml-modeline-vis-face ((t nil)))
 '(trailing-whitespace ((((class color) (background light)) (:background "#eeeeaa"))))
 '(visible-mark-face ((((class color) (background light)) (:background "yellow")))))

(put 'downcase-region 'disabled nil)
