(autoload 'highlight-symbol-at-point "highlight-symbol" nil t)
(autoload 'highlight-symbol-next "highlight-symbol" nil t)
(autoload 'highlight-symbol-prev "highlight-symbol" nil t)
(autoload 'highlight-symbol-next "highlight-symbol" nil t)
(autoload 'highlight-symbol-query-replace "highlight-symbol" nil t)
(autoload 'highlight-symbol-remove-all "highlight-symbol" nil t)
(global-set-key (kbd "C-s-<left>") 'highlight-symbol-prev)
(global-set-key (kbd "C-s-<right>") 'highlight-symbol-next)
(global-set-key (kbd "C-s-<pause>") 'highlight-symbol-prev)
(global-set-key (kbd "C-s-<268632083>") 'highlight-symbol-next)
(global-set-key (kbd "C-s-<spc>") 'highlight-symbol-at-point)
(global-set-key (kbd "C-s-<268632064>") 'highlight-symbol-at-point)
(global-set-key (kbd "C-s-5") 'highlight-symbol-query-replace)
(global-set-key (kbd "C-s-<backspace>") 'highlight-symbol-remove-all)

(autoload 'iedit-mode "iedit-mode" nil t)
(global-set-key (kbd "C-s-;") 'iedit-mode)

(autoload 'all "all")
(autoload 'iedit-mode "iedit")
(require 'color-moccur)
(require 'moccur-edit)

(require 'dabbrev-highlight)

(autoload 'bm-toggle   "bm" "Toggle bookmark in current buffer." t)
(autoload 'bm-next     "bm" "Goto bookmark."                     t)
(autoload 'bm-previous "bm" "Goto previous bookmark."            t)
(global-set-key (kbd "<C-s-up>") 'bm-previous)
(global-set-key (kbd "<C-s-down>") 'bm-next)
(global-set-key (kbd "C-s-/") 'bm-toggle)
(global-set-key (kbd "<left-fringe> <mouse-1>")
                #'(lambda(event)
                    (interactive "e")
                    (save-excursion (mouse-set-point event)
                                    (bm-toggle))))
